"""Generated by the release workflow; do not edit in a built package."""

BRIDGE_RELEASE_VERSION: str | None = "2.3.0"
BRIDGE_SHA256: dict[str, str] = {
    "fbchat-bridge-e2ee-darwin-amd64": "c6b1d9dc39dfc23238195f01764b196cc31eb62068c9a96abc41415a152d0fe2",
    "fbchat-bridge-e2ee-darwin-arm64": "c852505ca675b65e46d8e9f5cf0dbacc37d8d6802d6336db5fbdb03f973001d1",
    "fbchat-bridge-e2ee-linux-amd64": "00d83fee2825996666c85aa6c1a3214039371f7dc4a6e43f7c25b5b87d0b1a5b",
    "fbchat-bridge-e2ee-linux-arm64": "140956381eb5f1c45eb8bf2edba1983579c83be99fe98525b3e9e6f985401665",
    "fbchat-bridge-e2ee-windows-amd64.exe": "8dcd8ae81c4f74de805b11070b372de9efe99205b29f48fbd6e2eef89e6520dc",
}
