"""Bind and verify E2EE bridge checksums in final Python distributions."""

from __future__ import annotations

import argparse
import ast
import hashlib
import re
import sys
import tarfile
import zipfile
from pathlib import Path
from typing import Any

EXPECTED_BINARY_NAMES = frozenset(
    {
        "fbchat-bridge-e2ee-darwin-amd64",
        "fbchat-bridge-e2ee-darwin-arm64",
        "fbchat-bridge-e2ee-linux-amd64",
        "fbchat-bridge-e2ee-linux-arm64",
        "fbchat-bridge-e2ee-windows-amd64.exe",
    }
)
CHECKSUM_MODULE_MEMBER = "_messaging/_bridge_checksums.py"
SDIST_CHECKSUM_MODULE_SUFFIX = f"/src/{CHECKSUM_MODULE_MEMBER}"
_PROJECT_SECTION = re.compile(r"(?ms)^\[project\][ \t]*\r?\n(?P<body>.*?)(?=^\[|\Z)")
_VERSION = re.compile(r'(?m)^version[ \t]*=[ \t]*["\'](?P<version>[^"\']+)["\'][ \t]*$')
_MANIFEST_LINE = re.compile(
    r"^(?P<digest>[0-9a-f]{64})  (?P<name>fbchat-bridge-e2ee-[^/\\]+)$"
)


def read_project_version(project_file: Path) -> str:
    text = project_file.read_text(encoding="utf-8", errors="strict")
    project = _PROJECT_SECTION.search(text)
    if project is None:
        raise RuntimeError(f"Không tìm thấy [project] trong {project_file}")
    version = _VERSION.search(project.group("body"))
    if version is None:
        raise RuntimeError(f"Không tìm thấy project.version trong {project_file}")
    return version.group("version")


def validate_release_tag(release_tag: str, version: str) -> None:
    expected = f"v{version}"
    if release_tag != expected:
        raise RuntimeError(
            f"Release tag {release_tag!r} không khớp package version {expected!r}"
        )


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def collect_binary_digests(directory: Path) -> dict[str, str]:
    if not directory.is_dir():
        raise FileNotFoundError(f"Không tìm thấy thư mục bridge binary: {directory}")

    candidates = {
        path.name: path
        for path in directory.iterdir()
        if path.name.startswith("fbchat-bridge-e2ee-")
    }
    missing = sorted(EXPECTED_BINARY_NAMES - candidates.keys())
    unexpected = sorted(candidates.keys() - EXPECTED_BINARY_NAMES)
    if missing or unexpected:
        details: list[str] = []
        if missing:
            details.append(f"thiếu: {', '.join(missing)}")
        if unexpected:
            details.append(f"thừa: {', '.join(unexpected)}")
        raise RuntimeError("Bộ bridge binary không hợp lệ (" + "; ".join(details) + ")")

    for name, path in candidates.items():
        if path.is_symlink() or not path.is_file():
            raise RuntimeError(
                f"Bridge asset phải là regular file, không phải symlink: {name}"
            )

    return {name: sha256_file(candidates[name]) for name in sorted(candidates)}


def render_checksum_module(version: str, digests: dict[str, str]) -> str:
    lines = [
        '"""Generated by the release workflow; do not edit in a built package."""',
        "",
        f"BRIDGE_RELEASE_VERSION: str | None = {version!r}",
        "BRIDGE_SHA256: dict[str, str] = {",
    ]
    lines.extend(
        f"    {name!r}: {digest!r}," for name, digest in sorted(digests.items())
    )
    lines.extend(["}", ""])
    return "\n".join(lines)


def bind_checksums(
    binaries_dir: Path,
    module_path: Path,
    manifest_path: Path,
    *,
    version: str,
) -> dict[str, str]:
    digests = collect_binary_digests(binaries_dir)
    module_path.parent.mkdir(parents=True, exist_ok=True)
    module_path.write_text(
        render_checksum_module(version, digests), encoding="utf-8", newline="\n"
    )
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest = "".join(
        f"{digest}  {name}\n" for name, digest in sorted(digests.items())
    )
    manifest_path.write_text(manifest, encoding="ascii", newline="\n")
    return digests


def verify_manifest(manifest_path: Path, expected_digests: dict[str, str]) -> None:
    try:
        lines = manifest_path.read_text(encoding="ascii", errors="strict").splitlines()
    except FileNotFoundError as exc:
        raise RuntimeError(f"Không tìm thấy SHA-256 manifest: {manifest_path}") from exc

    actual: dict[str, str] = {}
    for line_number, line in enumerate(lines, start=1):
        match = _MANIFEST_LINE.fullmatch(line)
        if match is None:
            raise RuntimeError(
                f"SHA-256 manifest không hợp lệ ở dòng {line_number}: {manifest_path}"
            )
        name = match.group("name")
        if name in actual:
            raise RuntimeError(f"SHA-256 manifest chứa asset trùng: {name}")
        actual[name] = match.group("digest")

    if actual != expected_digests:
        raise RuntimeError("SHA-256 manifest không khớp năm bridge binary đã build")


def _parse_checksum_module(source: str, origin: str) -> tuple[str, dict[str, str]]:
    try:
        tree = ast.parse(source, filename=origin)
    except SyntaxError as exc:
        raise RuntimeError(f"Checksum module không parse được trong {origin}") from exc

    values: dict[str, Any] = {}
    for node in tree.body:
        target: ast.expr | None = None
        value: ast.expr | None = None
        if isinstance(node, ast.AnnAssign):
            target, value = node.target, node.value
        elif isinstance(node, ast.Assign) and len(node.targets) == 1:
            target, value = node.targets[0], node.value
        if isinstance(target, ast.Name) and target.id in {
            "BRIDGE_RELEASE_VERSION",
            "BRIDGE_SHA256",
        }:
            if value is None:
                raise RuntimeError(f"Giá trị checksum bị thiếu trong {origin}")
            try:
                values[target.id] = ast.literal_eval(value)
            except (ValueError, TypeError) as exc:
                raise RuntimeError(
                    f"Checksum module chứa giá trị động không an toàn trong {origin}"
                ) from exc

    version = values.get("BRIDGE_RELEASE_VERSION")
    digests = values.get("BRIDGE_SHA256")
    if not isinstance(version, str):
        raise RuntimeError(f"BRIDGE_RELEASE_VERSION không hợp lệ trong {origin}")
    if not isinstance(digests, dict) or not all(
        isinstance(name, str) and isinstance(digest, str)
        for name, digest in digests.items()
    ):
        raise RuntimeError(f"BRIDGE_SHA256 không hợp lệ trong {origin}")
    return version, digests


def _read_wheel_checksum_module(wheel: Path) -> str:
    with zipfile.ZipFile(wheel) as archive:
        members = [
            name for name in archive.namelist() if name == CHECKSUM_MODULE_MEMBER
        ]
        if len(members) != 1:
            raise RuntimeError(
                f"Wheel {wheel.name} phải chứa đúng một {CHECKSUM_MODULE_MEMBER}"
            )
        return archive.read(members[0]).decode("utf-8", errors="strict")


def _read_sdist_checksum_module(sdist: Path) -> str:
    with tarfile.open(sdist, mode="r:gz") as archive:
        members = [
            member
            for member in archive.getmembers()
            if member.isfile()
            and (
                member.name == f"src/{CHECKSUM_MODULE_MEMBER}"
                or member.name.endswith(SDIST_CHECKSUM_MODULE_SUFFIX)
            )
        ]
        if len(members) != 1:
            raise RuntimeError(
                f"Sdist {sdist.name} phải chứa đúng một src/{CHECKSUM_MODULE_MEMBER}"
            )
        handle = archive.extractfile(members[0])
        if handle is None:  # pragma: no cover - tarfile invariant
            raise RuntimeError(f"Không đọc được checksum module trong {sdist.name}")
        return handle.read().decode("utf-8", errors="strict")


def _find_single_distribution(dist_dir: Path, pattern: str, kind: str) -> Path:
    matches = sorted(path for path in dist_dir.glob(pattern) if path.is_file())
    if len(matches) != 1:
        raise RuntimeError(
            f"Cần đúng một {kind} trong {dist_dir}, tìm thấy {len(matches)}"
        )
    return matches[0]


def verify_distributions(
    binaries_dir: Path,
    dist_dir: Path,
    *,
    version: str,
    manifest_path: Path,
) -> tuple[Path, Path]:
    expected_digests = collect_binary_digests(binaries_dir)
    verify_manifest(manifest_path, expected_digests)
    wheel = _find_single_distribution(dist_dir, "*.whl", "wheel")
    sdist = _find_single_distribution(dist_dir, "*.tar.gz", "sdist")

    sources = {
        wheel.name: _read_wheel_checksum_module(wheel),
        sdist.name: _read_sdist_checksum_module(sdist),
    }
    for artifact, source in sources.items():
        embedded_version, embedded_digests = _parse_checksum_module(source, artifact)
        if embedded_version != version:
            raise RuntimeError(
                f"{artifact} nhúng bridge version {embedded_version!r}, cần {version!r}"
            )
        if embedded_digests != expected_digests:
            raise RuntimeError(
                f"{artifact} nhúng checksum không khớp năm bridge binary đã build"
            )
    return wheel, sdist


def _common_release_context(args: argparse.Namespace) -> str:
    version = read_project_version(args.project_file)
    validate_release_tag(args.release_tag, version)
    return version


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate = subparsers.add_parser("validate", help="Kiểm tra tag khớp version")
    validate.add_argument("--release-tag", required=True)
    validate.add_argument("--project-file", type=Path, default=Path("pyproject.toml"))

    bind = subparsers.add_parser("bind", help="Ghi checksum vào source trước khi build")
    bind.add_argument("--release-tag", required=True)
    bind.add_argument("--project-file", type=Path, default=Path("pyproject.toml"))
    bind.add_argument("--binaries-dir", type=Path, required=True)
    bind.add_argument("--module", type=Path, required=True)
    bind.add_argument("--manifest", type=Path, required=True)

    verify = subparsers.add_parser(
        "verify", help="Đối chiếu checksum trong wheel và sdist cuối cùng"
    )
    verify.add_argument("--release-tag", required=True)
    verify.add_argument("--project-file", type=Path, default=Path("pyproject.toml"))
    verify.add_argument("--binaries-dir", type=Path, required=True)
    verify.add_argument("--dist-dir", type=Path, required=True)
    verify.add_argument("--manifest", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    version = _common_release_context(args)
    if args.command == "bind":
        bind_checksums(
            args.binaries_dir,
            args.module,
            args.manifest,
            version=version,
        )
        print("Bound checksums for exactly five bridge binaries")
    elif args.command == "verify":
        wheel, sdist = verify_distributions(
            args.binaries_dir,
            args.dist_dir,
            version=version,
            manifest_path=args.manifest,
        )
        print(f"Checksum trong {wheel.name} và {sdist.name}: OK")
    else:
        print(f"Release tag v{version}: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
